### PR TITLE
Add gv-setters for ht-get and ht-get*.

### LINKED ISSUE #22: Allow for setf-able ht-get?
This can be done with something like `(gv-define-simple-setter ht-get ht-set)`.

### PR DESCRIPTION
**Pull request by Alexander-Miller**
Fixes #22.

### CODE REVIEW

**Comment by Alexander-Miller** [comment]
Looks gv was only introduced in 24.3. If you think so old a version is still worth supporting I can try and convince the compiler to exclude the gv bits on 24.2.

**Comment by Wilfred** [comment]
Nice! Thanks, this is worthwhile feature :)

Could you add an example to the readme? Also, I'm very happy to drop support for older Emacs versions, feel free to adjust the travis configuration file.

**Comment by Alexander-Miller** [comment]
Done and done.

**Comment by Wilfred** [comment]
Thanks! :tada:

**Pull request merged**
